### PR TITLE
Replace broccoli-filter with broccoli-persistent-filter

### PR DESCRIPTION
**Pull request by patocallaghan**
I know you have a WIP PR in https://github.com/wyeworks/ember-qunit-nice-errors/pull/55 but I have a working PR with broccoli-persistent-filter which we are using in our app. It gives us substantial performance gains, reducing warm build times by ~15 seconds over current `master` (we have a lot of tests!).

### CODE REVIEW

**Comment by san650** [comment]
This is great!! Thanks @patocallaghan for contributing.

**Comment by fedekau** [comment]
@patocallaghan Probably this week 😄

**Comment by fedekau** [comment]
@patocallaghan checkout [v1.2.0](https://github.com/wyeworks/ember-qunit-nice-errors/releases/tag/v1.2.0)

**Comment by patocallaghan** [comment]
@fedekau Thank you!

**Pull request merged**
