### PR TITLE
Improve messages

### PR DESCRIPTION
**Pull request by sdebarros**
@acostami I would add an `at` to separate the assert from the file and line info on the message

`assert.ok(true) at file_path.js:[line]:[column]`

### CODE REVIEW

**Comment by fedekau** [comment]
@acostami & @sdebarros I haven't check if it is possible, but if we could have the full file path in the project it would be even better I think, because if you have two files with the same name only having that might be confusing.

**Comment by acostami** [comment]
@sdebarros excellent! We'll also need to update the readme images accordingly to the new format and also update `notEqual` tests.

**Comment by san650** [comment]
How about using the same messages than mocha + chai?

They use phrases like

```
assert.equal(foo, bar); // => expected foo to equal bar
assert.ok(foo); // => expected foo to be truthy
assert.notOk(foo); // => expected foo to be falsy
```

etc.

**Comment by fedekau** [comment]
I like this proposed format @san650 but I would still leave the path and line number, that's really useful! 

Something like `assert.ok(foo) at file_path.js:[line]:[column] expected foo to be truthy`

**Comment by san650** [comment]
I agree that having the file path and line number it's really useful, but I wouldn't add that by default. We might be adding too much noise by default, maybe we can add a preference to turn the feature on?.

Something like

```js
ENV['ember-qunit-nice-errors'] = {
  showFilePathAndLineNumber: true
};
```

Also, I would print the assertion as

```
expected foo to be truthy at pat/to/test/file-test.js:[line]
```

without the `assert.ok(...)` and without the column line (is it needed?)

Just my 2¢

**Comment by sdebarros** [comment]
I agree on adding the preference for the file and line number, but for the message I think I prefer rspec's approach of showing the actual faulting code:

```
Failure/Error: my_method.should == 2
  expected: 2
       got: 3 (using ==)
```
I think it's easier to see the error and find it on the test (specially if we are not adding the file/line by default), but it's just a preference.

**Pull request merged**
