### PR TITLE
update recast version

### LINKED ISSUE #51: Does not support async/await
There was some test files that were completely ignored by `ember-qunit-nice-errors` and I did not understood why.

It turned out that is silently fails during transform:

```
{ Error: Line 42: Unexpected identifier
    at ErrorHandler.constructError (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:3414:27)
    at JSXParser.Parser.unexpectedTokenError (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:542:39)
    at JSXParser.Parser.throwUnexpectedToken (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:552:21)
    at JSXParser.Parser.consumeSemicolon (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:845:23)
    at JSXParser.Parser.parseLexicalDeclaration (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:1892:15)
    at JSXParser.Parser.parseStatementListItem (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:1815:69)
    at JSXParser.Parser.parseFunctionSourceElements (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:2586:29)
    at JSXParser.Parser.parseFunctionExpression (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:2763:26)
    at JSXParser.Parser.parsePrimaryExpression (/Users/anthony/dev/cogniteev/oncrawl-web-client/node_modules/ember-qunit-nice-errors/node_modules/esprima/dist/esprima.js:931:38)
  index: 1717,
  lineNumber: 42,
  description: 'Unexpected identifier' }
```

On lines such as:

```js
  let model = await subject.model();
```

The currently used version of `recast` is using `esprima@3.1.0` whereas the `async/await` support was introduced (from what I found) in `esprima@4.0.0`.

The latest version of `recast` does use `esprima@4.0.0`.

### PR DESCRIPTION
**Pull request by panthony**
This PR updates the `recast` version to the latest in order to update the underlying `esprima` dependency.

This update allows the usage of ECMAScript 2017 features such as async/await.

It fix #51

### CODE REVIEW

**Comment by san650** [comment]
Thanks @panthony for the PR. I've triggered another build of Travis because it was throwing a weird error on one of the targets.

If everything runs ok in travis, we'll merge it :)

Thanks!!

**Comment by fedekau** [comment]
@san650 I have done that already, but it got stucked as the previous build did 😢 Let's wait for this one though

**Comment by fedekau** [comment]
@panthony Seems to a problem with `phantomjs`. I will do a new PR replacing `phantomjs` with `chrome` and after that your PR should be good to go 😄 .

**Comment by panthony** [comment]
@fedekau @san650 Thanks you both !

**Comment by fedekau** [comment]
Thank you @panthony! And by the way `v1.1.3` was released with this fix, see https://github.com/wyeworks/ember-qunit-nice-errors/releases/tag/v1.1.3

**Pull request merged**
