### PR TITLE
Allow to configure include and exclude rules

### LINKED ISSUE #20: Add option to exclude files from being processed
A nice feature to have would be an option to exclude file from being processed by the addon, something like `"exclude" : [file1, file2,... ]` or maybe using a regular expression or both!

### PR DESCRIPTION
**Pull request by san650**
Closes #20

### CODE REVIEW

**Review by fedekau — APPROVED** [review]
This is great @san650 !

**Comment by fedekau** [comment]
Is this ready to merge?

**Comment by san650** [comment]
@fedekau it is! My only question/concern is if we should cache the minimatch matchers... I think it compiles them to a regex on each call.

Maybe this is a good first step and we can refine it later.

**Comment by fedekau** [comment]
@san650 I think it is fine as it is right now, we can come back on this if it turns out to be too slow

**Pull request merged**
